### PR TITLE
Update installation page

### PR DESCRIPTION
**Pull request by prathamesh-sonpatki**

### CODE REVIEW

**Comment by prathamesh-sonpatki** [comment]
@IndianGuru @kotp Please review.

**Comment by kotp** [comment]
Wait a second,so are we migrating from Hugo to Jekyll?  And why did this effect the footer?

**Comment by kotp** [comment]
Ah, it looks like this commit not only has the web page update files, but also some infrastructure being carried along with it.  The gemfile probably has nothing to do with this update.  @prathamesh-sonpatki can you clean this pull request up?  Sorry for the delay in finding this problem.

**Comment by prathamesh-sonpatki** [comment]
@kotp Hugo is used on `rubylearning.com/blog`. This commit is related to `rubylearning.com`. I added `github-pages` because we are already using it in production. Does it break anything?

**Comment by kotp** [comment]
Sorry, I misread the name of the repository.  Nothing that I can see then. :)

**Comment by prathamesh-sonpatki** [comment]
:smile:

**Pull request merged**
